### PR TITLE
Certora

### PR DESCRIPTION
**Pull request by mdgeorge4153**
Handing off Certora's work.

### CODE REVIEW

**Review by zareth-san — CHANGES_REQUESTED** [review]
Hey @mdgeorge4153 thanks for the PR!

I ran the scripts for the non SeriesController and the reports look good except for 2 unexpected failing tests in the ERC1155Controller spec from running `sh certora/scripts/verifyERC1155Controller.sh "verify certora PR"`. The tests are: `controller_initialized` and `initialization_single_call`. The report is here:

https://vaas-stg.certora.com/output/92909/f2f7301e42a513d415a3/?anonymousKey=ce1bfce3de612847527d9d77a179f0be58075cfe#controller_initializedResults

I verified in a test that the `ERC1155Controller.__ERC1155Controller_init` function reverts when called twice.

I can't tell from the report what input parameters cause this... nor from the test. Any idea on why those are failing?

**Comment by mdgeorge4153** [comment]
I talked with Nick about the failing rules.  One of them (controller_initialized) fails because it is possible to pass in 0 as the controller argument to initialization, so we recommend requiring that it's nonzero.  If that's a non-issue then we can remove that rule or prevent it from running on the initializer.  The other failure seems to be a bug in a rule, I will update the PR to remove the rule this afternoon, since you already have unit tests covering that case

**Comment by mdgeorge4153** [comment]
We discovered some potential problems with the verification configuration while reviewing; converted to draft, will update.

**Comment by mdgeorge4153** [comment]
Closing this PR because it is very stale

**Pull request closed without merging**
